#!/usr/bin/env bash

folder=(bin i3 nvim tmux uwuntu zsh)
DOTFILES=$HOME/personal/dotfiles

pushd $DOTFILES

for i in "${folder[@]}"
do
  echo "stow $i"
  stow -D $i
  stow $i --target=$HOME
done

popd
